---
title: "ddp_w4_presentation"
author: Pablo Leon
date: 2018-09-24
output: slidy_presentation
---


Word Cloud Pitch
========================================================

Surveys usually collects certain attributtes of the subject using
written text.

This happens even when the questionnaire presents a limited set of options.

This allows to capture options that were not anticipated on the form design
or for options that are expected to have very low frequency, so not worthy of include as explicit option in the form.



Word Cloud Pitch ...
========================================================

This brings a problem that the same option can be written in several different forms.

Those different forms have to be normalized and assigned to a valid option.

The intention of the application is to show how many different forms each
of the valid options had on a survey.

The case displayed is the question on the originary people of chile self-identification
of a certain survey.


Word Cloud Pitch ...
========================================================

There are several reasons for the variations on the way an option can be written.

>- ( a ) Sometimes the category have many alternative names.
>- ( b ) Sometimes the text describe a situation which is interpreted by the survey team as a corresponding to a category
>- ( c ) Othertimes the text is pooly written, with spelling errors or just because the pollster is not familiar with the word, or with poor optical character recognition.



Word Cloud Pitch ...
========================================================

This are examples of each case.

```{r echo=FALSE}

suppressPackageStartupMessages({
library(tibble)
library(dplyr)
})

lstCase <- list(
  a = c( "ARAUCANO" = "Alternative name")
  ,b = c( "FRANCESA MAPUCHE" = "Mixed descendence"
           ,"MADUGUNDUN" = "The language of Mapuche people"
           ,"MADRE MAPUCHE" = "Mother is Mapuche, accepted self-identification")
  ,c = c( "MACHUPE" = "Wrong spelling"
            , "HAPUCHE" = "probably OCR"
            , "AIAUCANO" = "probably OCR"
            )
)


dfCases <- lapply(names(lstCase), function(name) {
  vText <- lstCase[[ name   ]]
  nLen <- length(vText)
  vCat <- rep(name, nLen)
  
  tibble( Case = vCat, Text = names(vText), Description = unname(vText))
}) %>% bind_rows()

dfCases
```


Word Cloud Pitch ...
========================================================

Then in order to best display the relative differences in alternative cases 
for each category, a function is introduced to reduce the difference, 
so the user can try with:

- Quantity : "true" values
- log() : Logarithm of the Quantity, minimum contrast between values
- sqrt() : Square root of the Quantity, higher contrast with respect to log()


